In [ ]:
!nvidia-smi

Wed Sep 23 09:32:17 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   43C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [ ]:
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print(
        "VRAM (GB):",
        round(
            torch.cuda.get_device_properties(0).total_memory / 1024**3,
            2
        )
    )

PyTorch version: 2.11.0+cu128
CUDA available: True
GPU: Tesla T4
VRAM (GB): 14.56

In [ ]:
!pip install unsloth

Requirement already satisfied: unsloth in /usr/local/lib/python3.13/dist-packages (2026.9.10)
Requirement already satisfied: unsloth_zoo>=2026.9.7 in /usr/local/lib/python3.13/dist-packages (from unsloth) (2026.9.7)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.13/dist-packages (from unsloth) (0.48.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from unsloth) (26.3)
Requirement already satisfied: torch<2.13.0,>=2.4.0 in /usr/local/lib/python3.13/dist-packages (from unsloth) (2.11.0+cu128)
Requirement already satisfied: torchvision in /usr/local/lib/python3.13/dist-packages (from unsloth) (0.26.0+cu128)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from unsloth) (2.1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from unsloth) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.13/dist-packages (from unsloth) (5.9.5)
Requirement already satisfied: tyro in /usr/local/lib/python3.13/dist-packages (from unsloth) (1.0.16)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from unsloth) (5.29.6)
Requirement already satisfied: xformers>=0.0.27.post2 in /usr/local/lib/python3.13/dist-packages (from unsloth) (0.0.35)
Requirement already satisfied: bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5 in /usr/local/lib/python3.13/dist-packages (from unsloth) (0.50.2)
Requirement already satisfied: triton>=3.0.0 in /usr/local/lib/python3.13/dist-packages (from unsloth) (3.6.0)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from unsloth) (0.2.2)
Requirement already satisfied: datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1 in /usr/local/lib/python3.13/dist-packages (from unsloth) (4.3.0)
Requirement already satisfied: accelerate>=0.34.1 in /usr/local/lib/python3.13/dist-packages (from unsloth) (1.14.0)
Requirement already satisfied: peft!=0.11.0,>=0.18.0 in /usr/local/lib/python3.13/dist-packages (from unsloth) (0.20.0)
Requirement already satisfied: huggingface_hub>=0.34.0 in /usr/local/lib/python3.13/dist-packages (from unsloth) (1.29.0)
Requirement already satisfied: hf_transfer in /usr/local/lib/python3.13/dist-packages (from unsloth) (0.1.9)
Requirement already satisfied: diffusers in /usr/local/lib/python3.13/dist-packages (from unsloth) (0.40.0)
Requirement already satisfied: transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3 in /usr/local/lib/python3.13/dist-packages (from unsloth) (5.5.0)
Requirement already satisfied: trl!=0.19.0,<=0.24.0,>=0.18.2 in /usr/local/lib/python3.13/dist-packages (from unsloth) (0.24.0)
Requirement already satisfied: typer>=0.12.0 in /usr/local/lib/python3.13/dist-packages (from unsloth) (0.27.2)
Requirement already satisfied: pydantic in /usr/local/lib/python3.13/dist-packages (from unsloth) (2.13.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from unsloth) (6.0.3)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.13/dist-packages (from unsloth) (1.6.0)
Requirement already satisfied: structlog>=24.1.0 in /usr/local/lib/python3.13/dist-packages (from unsloth) (26.1.0)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.13/dist-packages (from unsloth) (8.5.0)
Requirement already satisfied: rich in /usr/local/lib/python3.13/dist-packages (from unsloth) (13.9.4)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.13/dist-packages (from accelerate>=0.34.1->unsloth) (0.8.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.32.5)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (23.0.1)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.4.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (4.0.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.70.16)
Requirement already satisfied: fsspec<=2025.9.0,>=2023.1.0 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2025.9.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.34.0->unsloth) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.34.0->unsloth) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (3.4.5)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (12.8.90)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.13/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth) (0.22.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer>=0.12.0->unsloth) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer>=0.12.0->unsloth) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich->unsloth) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich->unsloth) (2.21.0)
Requirement already satisfied: torchao>=0.13.0 in /usr/local/lib/python3.13/dist-packages (from unsloth_zoo>=2026.9.7->unsloth) (0.18.0)
Requirement already satisfied: cut_cross_entropy in /usr/local/lib/python3.13/dist-packages (from unsloth_zoo>=2026.9.7->unsloth) (25.1.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.13/dist-packages (from unsloth_zoo>=2026.9.7->unsloth) (11.3.0)
Requirement already satisfied: msgspec in /usr/local/lib/python3.13/dist-packages (from unsloth_zoo>=2026.9.7->unsloth) (0.21.1)
Requirement already satisfied: importlib_metadata in /usr/local/lib/python3.13/dist-packages (from diffusers->unsloth) (9.0.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic->unsloth) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic->unsloth) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic->unsloth) (0.4.4)
Requirement already satisfied: docstring-parser>=0.16 in /usr/local/lib/python3.13/dist-packages (from tyro->unsloth) (0.18.0)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from tyro->unsloth) (4.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<13,>=12.9.4->torch<2.13.0,>=2.4.0->unsloth) (1.8.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.14.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.19)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.16.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich->unsloth) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch<2.13.0,>=2.4.0->unsloth) (1.3.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.13/dist-packages (from importlib_metadata->diffusers->unsloth) (4.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch<2.13.0,>=2.4.0->unsloth) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.24.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.17.0)

In [ ]:
from unsloth import FastLanguageModel
import torch

print("Unsloth imported successfully")

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
Unsloth imported successfully

In [ ]:
max_seq_length = 2048
dtype = None
load_in_4bit = True

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Llama-3.2-3B-Instruct-bnb-4bit",
    max_seq_length=max_seq_length,
    dtype=dtype,
    load_in_4bit=load_in_4bit,
)

print("Model loaded successfully!")

==((====))==  Unsloth 2026.9.10: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

Unsloth: Will load unsloth/Llama-3.2-3B-Instruct-bnb-4bit as a legacy tokenizer.

Model loaded successfully!

In [ ]:
FastLanguageModel.for_inference(model)

print("Inference mode enabled")

Inference mode enabled

In [ ]:
prompt = (
    "Image rejected due to blur=85, contrast=40, state=REJECT. "
    "Explain the defect and give a one-sentence retake instruction. "
    "Use only the information provided. Do not invent measurements, "
    "focus values, or other technical parameters."
)

inputs = tokenizer(
    [prompt],
    return_tensors="pt"
).to("cuda")

outputs = model.generate(
    **inputs,
    max_new_tokens=100,
    use_cache=True
)

response = tokenizer.batch_decode(
    outputs,
    skip_special_tokens=True
)[0]

print(response)

Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Image rejected due to blur=85, contrast=40, state=REJECT. Explain the defect and give a one-sentence retake instruction. Use only the information provided. Do not invent measurements, focus values, or other technical parameters. The image is rejected because the focus is not sharp. Retake the image to ensure that the object is in sharp focus. Retake the image to ensure the object is in sharp focus. Retake the image to ensure the object is in sharp focus. (No change in response) Retake the image to ensure the object is in sharp focus. Retake the image to ensure the object is in sharp focus. Retake the blur value to ensure the image is in sharp focus. Retake the

In [ ]:
print("===== M1 DAY 1 SMOKE TEST =====")
print("GPU:", torch.cuda.get_device_name(0))
print("CUDA available:", torch.cuda.is_available())
print("VRAM (GB):", round(
    torch.cuda.get_device_properties(0).total_memory / 1024**3, 2
))
print("Model: unsloth/Llama-3.2-3B-Instruct-bnb-4bit")
print("4-bit loading: True")
print()
print("GENERATED OUTPUT:")
print(response)

===== M1 DAY 1 SMOKE TEST =====
GPU: Tesla T4
CUDA available: True
VRAM (GB): 14.56
Model: unsloth/Llama-3.2-3B-Instruct-bnb-4bit
4-bit loading: True

GENERATED OUTPUT:
Image rejected due to blur=85, contrast=40, state=REJECT. Explain the defect and give a one-sentence retake instruction. Use only the information provided. Do not invent measurements, focus values, or other technical parameters. The image is rejected because the focus is not sharp. Retake the image to ensure that the object is in sharp focus. Retake the image to ensure the object is in sharp focus. Retake the image to ensure the object is in sharp focus. (No change in response) Retake the image to ensure the object is in sharp focus. Retake the image to ensure the object is in sharp focus. Retake the blur value to ensure the image is in sharp focus. Retake the

In [ ]:
import torch
from unsloth import FastLanguageModel

MODEL_NAME = "unsloth/Llama-3.2-3B-Instruct-bnb-4bit"

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=MODEL_NAME,
    max_seq_length=2048,
    load_in_4bit=True,
)

print("Model loaded")
print("Tokenizer loaded")
print("Chat template available:", tokenizer.chat_template is not None)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print(
        "VRAM:",
        round(
            torch.cuda.get_device_properties(0).total_memory / 1024**3,
            2,
        ),
        "GB",
    )

==((====))==  Unsloth 2026.9.10: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

Unsloth: Will load unsloth/Llama-3.2-3B-Instruct-bnb-4bit as a legacy tokenizer.

Model loaded
Tokenizer loaded
Chat template available: True
CUDA available: True
GPU: Tesla T4
VRAM: 14.56 GB

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving train_chat.jsonl to train_chat.jsonl
Saving val_chat.jsonl to val_chat.jsonl

In [ ]:
from datasets import load_dataset

dataset = load_dataset(
    "json",
    data_files={
        "train": "/content/train_chat.jsonl",
        "val": "/content/val_chat.jsonl",
    },
)

print(dataset)
print(dataset["train"][0])

Generating train split: 0 examples [00:00, ? examples/s]

Generating val split: 0 examples [00:00, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['messages'],
        num_rows: 450
    })
    val: Dataset({
        features: ['messages'],
        num_rows: 50
    })
})
{'messages': [{'role': 'system', 'content': 'You are a clinical imaging quality assistant. Given DICOM quality metrics (blur, contrast, noise scores, overall state, and dominant defect), explain the defect and give a concise, actionable retake instruction.'}, {'role': 'user', 'content': '{"blur": 4.4, "contrast": 51.2, "noise": 25.1, "state": "ACCEPT", "dominant_defect": "none"}'}, {'role': 'assistant', 'content': 'All reported quality metrics are within the acceptable range. No retake is needed.'}]}

In [ ]:
import torch
from unsloth import FastLanguageModel

model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
    ],
    lora_alpha=16,
    lora_dropout=0,
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=42,
)

print("LoRA adapter configured successfully.")

Unsloth 2026.9.10 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.

LoRA adapter configured successfully.

In [ ]:
model.print_trainable_parameters()

trainable params: 24,313,856 || all params: 3,237,063,680 || trainable%: 0.7511

In [ ]:
def format_batch(examples):
    texts = []

    for messages in examples["messages"]:
        text = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=False,
        )
        texts.append(text)

    return {"text": texts}


dataset_text = dataset.map(
    format_batch,
    batched=True,
    remove_columns=["messages"],
)

print(dataset_text)
print(dataset_text["train"][0])

NameError: name 'dataset' is not defined

In [ ]:
print(dataset_text["train"][0]["text"])

<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 23 Sep 2026

You are a clinical imaging quality assistant. Given DICOM quality metrics (blur, contrast, noise scores, overall state, and dominant defect), explain the defect and give a concise, actionable retake instruction.<|eot_id|><|start_header_id|>user<|end_header_id|>

{"blur": 4.4, "contrast": 51.2, "noise": 25.1, "state": "ACCEPT", "dominant_defect": "none"}<|eot_id|><|start_header_id|>assistant<|end_header_id|>

All reported quality metrics are within the acceptable range. No retake is needed.<|eot_id|>

In [ ]:
import accelerate
import transformers
import trl
import unsloth
import unsloth_zoo
import torch

print("accelerate:", accelerate.__version__)
print("transformers:", transformers.__version__)
print("trl:", trl.__version__)
print("unsloth:", getattr(unsloth, "__version__", "unknown"))
print("unsloth_zoo:", getattr(unsloth_zoo, "__version__", "unknown"))
print("torch:", torch.__version__)

accelerate: 1.14.0
transformers: 5.5.0
trl: 0.24.0
unsloth: 2026.9.10
unsloth_zoo: 2026.9.7
torch: 2.11.0+cu128

In [ ]:
!pip install -U "accelerate==1.15.0"

Collecting accelerate==1.15.0
  Downloading accelerate-1.15.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from accelerate==1.15.0) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from accelerate==1.15.0) (26.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.13/dist-packages (from accelerate==1.15.0) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from accelerate==1.15.0) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from accelerate==1.15.0) (2.11.0+cu128)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.13/dist-packages (from accelerate==1.15.0) (1.29.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.13/dist-packages (from accelerate==1.15.0) (0.8.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.21.0->accelerate==1.15.0) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.21.0->accelerate==1.15.0) (3.32.5)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.21.0->accelerate==1.15.0) (2025.9.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.21.0->accelerate==1.15.0) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.21.0->accelerate==1.15.0) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.21.0->accelerate==1.15.0) (4.67.3)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.21.0->accelerate==1.15.0) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate==1.15.0) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate==1.15.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate==1.15.0) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate==1.15.0) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate==1.15.0) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate==1.15.0) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate==1.15.0) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate==1.15.0) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate==1.15.0) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate==1.15.0) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate==1.15.0) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate==1.15.0) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate==1.15.0) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate==1.15.0) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate==1.15.0) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate==1.15.0) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate==1.15.0) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate==1.15.0) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate==1.15.0) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate==1.15.0) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate==1.15.0) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate==1.15.0) (12.8.90)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=2.0.0->accelerate==1.15.0) (1.8.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate==1.15.0) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate==1.15.0) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate==1.15.0) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate==1.15.0) (3.19)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate==1.15.0) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate==1.15.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=2.0.0->accelerate==1.15.0) (3.0.3)
Downloading accelerate-1.15.0-py3-none-any.whl (394 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.3/394.3 kB 16.8 MB/s eta 0:00:00
Installing collected packages: accelerate
  Attempting uninstall: accelerate
    Found existing installation: accelerate 1.14.0
    Uninstalling accelerate-1.14.0:
      Successfully uninstalled accelerate-1.14.0
Successfully installed accelerate-1.15.0

In [ ]:
import accelerate
import transformers
import trl
import unsloth
import torch

print("accelerate:", accelerate.__version__)
print("transformers:", transformers.__version__)
print("trl:", trl.__version__)
print("unsloth:", getattr(unsloth, "__version__", "unknown"))
print("torch:", torch.__version__)

/usr/local/lib/python3.13/dist-packages/unsloth/__init__.py:1568: UserWarning: WARNING: Unsloth should be imported before [trl, transformers] to ensure all optimizations are applied. Your code may run slower or encounter memory issues without these optimizations.

Please restructure your imports with 'import unsloth' at the top of your file.
  from ._gpu_init import *

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
accelerate: 1.15.0
transformers: 5.5.0
trl: 0.24.0
unsloth: 2026.9.10
torch: 2.11.0+cu128

In [ ]:
import unsloth

from unsloth import FastLanguageModel
from datasets import load_dataset
from trl import SFTTrainer, SFTConfig
from transformers import TrainingArguments
import torch

print("Unsloth:", unsloth.__version__)
print("CUDA:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print(
        "VRAM:",
        round(
            torch.cuda.get_device_properties(0).total_memory / 1024**3,
            2
        ),
        "GB"
    )

Unsloth: 2026.9.10
CUDA: True
GPU: Tesla T4
VRAM: 14.56 GB

In [ ]:
from accelerate import Accelerator

acc = Accelerator()

print("is_fsdp2 available:", hasattr(acc.state, "is_fsdp2"))
print("Distributed type:", acc.state.distributed_type)

is_fsdp2 available: True
Distributed type: DistributedType.NO

In [ ]:
import unsloth

from unsloth import FastLanguageModel
import torch

MODEL_NAME = "unsloth/Llama-3.2-3B-Instruct-bnb-4bit"

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=MODEL_NAME,
    max_seq_length=2048,
    load_in_4bit=True,
)

print("Model loaded successfully")
print("Chat template available:", tokenizer.chat_template is not None)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print(
        "VRAM:",
        round(
            torch.cuda.get_device_properties(0).total_memory / 1024**3,
            2,
        ),
        "GB",
    )

==((====))==  Unsloth 2026.9.10: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

Unsloth: Will load unsloth/Llama-3.2-3B-Instruct-bnb-4bit as a legacy tokenizer.

Model loaded successfully
Chat template available: True
CUDA available: True
GPU: Tesla T4
VRAM: 14.56 GB

In [ ]:
from google.colab import files

uploaded = files.upload()

In [ ]:
from datasets import load_dataset

dataset = load_dataset(
    "json",
    data_files={
        "train": "/content/train_chat.jsonl",
        "val": "/content/val_chat.jsonl",
    },
)

print(dataset)
print(dataset["train"][0])

DatasetDict({
    train: Dataset({
        features: ['messages'],
        num_rows: 450
    })
    val: Dataset({
        features: ['messages'],
        num_rows: 50
    })
})
{'messages': [{'role': 'system', 'content': 'You are a clinical imaging quality assistant. Given DICOM quality metrics (blur, contrast, noise scores, overall state, and dominant defect), explain the defect and give a concise, actionable retake instruction.'}, {'role': 'user', 'content': '{"blur": 4.4, "contrast": 51.2, "noise": 25.1, "state": "ACCEPT", "dominant_defect": "none"}'}, {'role': 'assistant', 'content': 'All reported quality metrics are within the acceptable range. No retake is needed.'}]}

In [ ]:
def format_batch(examples):
    texts = []

    for messages in examples["messages"]:
        text = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=False,
        )
        texts.append(text)

    return {"text": texts}


dataset_text = dataset.map(
    format_batch,
    batched=True,
    remove_columns=["messages"],
)

print(dataset_text)
print(dataset_text["train"][0]["text"])

Map:   0%|          | 0/450 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['text'],
        num_rows: 450
    })
    val: Dataset({
        features: ['text'],
        num_rows: 50
    })
})
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 23 Sep 2026

You are a clinical imaging quality assistant. Given DICOM quality metrics (blur, contrast, noise scores, overall state, and dominant defect), explain the defect and give a concise, actionable retake instruction.<|eot_id|><|start_header_id|>user<|end_header_id|>

{"blur": 4.4, "contrast": 51.2, "noise": 25.1, "state": "ACCEPT", "dominant_defect": "none"}<|eot_id|><|start_header_id|>assistant<|end_header_id|>

All reported quality metrics are within the acceptable range. No retake is needed.<|eot_id|>

In [ ]:
from unsloth import FastLanguageModel

model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
    ],
    lora_alpha=16,
    lora_dropout=0,
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=42,
)

model.print_trainable_parameters()

Unsloth 2026.9.10 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.

trainable params: 24,313,856 || all params: 3,237,063,680 || trainable%: 0.7511

In [ ]:
import torch
from trl import SFTTrainer, SFTConfig

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

training_args = SFTConfig(
    output_dir="outputs_smoke_test_eval",
    max_steps=30,

    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=4,

    warmup_steps=5,
    learning_rate=2e-4,

    logging_steps=1,
    logging_first_step=True,

    eval_strategy="steps",
    eval_steps=10,

    fp16=not torch.cuda.is_bf16_supported(),
    bf16=torch.cuda.is_bf16_supported(),

    optim="adamw_8bit",

    max_length=2048,
    dataset_text_field="text",

    report_to="none",
    seed=42,
)

trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset_text["train"],
    eval_dataset=dataset_text["val"],
    processing_class=tokenizer,
)

print("SFTTrainer configured successfully.")

Unsloth: We found double BOS tokens - we shall remove one automatically.

Unsloth: Tokenizing ["text"] (num_proc=2):   0%|          | 0/450 [00:00<?, ? examples/s]

Unsloth: We found double BOS tokens - we shall remove one automatically.

Unsloth: Tokenizing ["text"] (num_proc=2):   0%|          | 0/50 [00:00<?, ? examples/s]

🦥 Unsloth: Padding-free auto-enabled, enabling faster training.
SFTTrainer configured successfully.

In [ ]:
print("Train rows:", len(trainer.train_dataset))
print("Eval rows:", len(trainer.eval_dataset))
print("Max length:", trainer.args.max_length)
print("Max steps:", trainer.args.max_steps)

Train rows: 450
Eval rows: 50
Max length: 2048
Max steps: 30

In [ ]:
trainer_stats = trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 450 | Num Epochs = 1 | Total steps = 30
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 24,313,856 of 3,237,063,680 (0.75% trained)
`use_return_dict` is deprecated! Use `return_dict` instead!
/usr/local/lib/python3.13/dist-packages/unsloth/import_fixes.py:3239: UserWarning: 'has_cuda' is deprecated, please use 'torch.backends.cuda.is_built()'
  return original(name)
/usr/local/lib/python3.13/dist-packages/unsloth/import_fixes.py:3239: UserWarning: 'has_cudnn' is deprecated, please use 'torch.backends.cudnn.is_available()'
  return original(name)
/usr/local/lib/python3.13/dist-packages/unsloth/import_fixes.py:3239: UserWarning: 'has_mps' is deprecated, please use 'torch.backends.mps.is_built()'
  return original(name)
/usr/local/lib/python3.13/dist-packages/unsloth/import_fixes.py:3239: UserWarning: 'has_mkldnn' is deprecated, please use 'torch.backends.mkldnn.is_available()'
  return original(name)

Unsloth: Restored added_tokens_decoder metadata in outputs_smoke_test_eval/checkpoint-30/tokenizer_config.json.

In [ ]:
!nvidia-smi

Wed Sep 23 09:39:49 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   69C    P0             32W /   70W |    2761MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            3503      C   /usr/bin/python3                       2758MiB |
+-----------------------------------------------------------------------------------------+

In [ ]:
print("Peak allocated:",
      round(torch.cuda.max_memory_allocated() / 1024**3, 2), "GB")

print("Peak reserved:",
      round(torch.cuda.max_memory_reserved() / 1024**3, 2), "GB")

Peak allocated: 2.64 GB
Peak reserved: 2.82 GB

In [ ]:
from unsloth import FastLanguageModel

FastLanguageModel.for_inference(model)

test_input = (
    '{"blur": 85.2, "contrast": 40.1, "noise": 12.4, '
    '"state": "REJECT", "dominant_defect": "motion_blur"}'
)

messages = [
    {
        "role": "system",
        "content": (
            "You are a clinical imaging quality assistant. "
            "Given DICOM quality metrics (blur, contrast, noise scores, "
            "overall state, and dominant defect), explain the defect and "
            "give a concise, actionable retake instruction."
        ),
    },
    {
        "role": "user",
        "content": test_input,
    },
]

inputs = tokenizer.apply_chat_template(
    messages,
    tokenize=True,
    add_generation_prompt=True,
    return_tensors="pt",
    return_dict=True,
).to("cuda")

outputs = model.generate(
    input_ids=inputs["input_ids"],
    attention_mask=inputs["attention_mask"],
    max_new_tokens=80,
    use_cache=True,
)

print(tokenizer.decode(outputs[0], skip_special_tokens=True))

Both `max_new_tokens` (=80) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

system

Cutting Knowledge Date: December 2023
Today Date: 23 Sep 2026

You are a clinical imaging quality assistant. Given DICOM quality metrics (blur, contrast, noise scores, overall state, and dominant defect), explain the defect and give a concise, actionable retake instruction.user

{"blur": 85.2, "contrast": 40.1, "noise": 12.4, "state": "REJECT", "dominant_defect": "motion_blur"}assistant

The image shows moderate motion blur (score 85/100). Review the acquisition and repeat the image.

In [ ]:
print(
    "Peak allocated:",
    round(torch.cuda.max_memory_allocated() / 1024**3, 2),
    "GB"
)

print(
    "Peak reserved:",
    round(torch.cuda.max_memory_reserved() / 1024**3, 2),
    "GB"
)

Peak allocated: 2.64 GB
Peak reserved: 2.82 GB

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

CHECKPOINT_DIR = "/content/drive/MyDrive/clinical-gatekeeper-checkpoints"

Mounted at /content/drive

In [ ]:
import os

os.makedirs(CHECKPOINT_DIR, exist_ok=True)

print("Checkpoint directory:", CHECKPOINT_DIR)
print("Exists:", os.path.isdir(CHECKPOINT_DIR))
print("Contents:", os.listdir(CHECKPOINT_DIR))

Checkpoint directory: /content/drive/MyDrive/clinical-gatekeeper-checkpoints
Exists: True
Contents: ['checkpoint-800', 'checkpoint-1000', 'checkpoint-1200', 'README.md']

In [ ]:
!pip install -q "accelerate==1.15.0" "transformers==5.5.0" "trl==0.24.0" "unsloth==2026.9.10"

In [ ]:
import unsloth
import torch
import transformers
import trl
import accelerate

print("unsloth:", unsloth.__version__)
print("transformers:", transformers.__version__)
print("trl:", trl.__version__)
print("accelerate:", accelerate.__version__)
print("torch:", torch.__version__)
print("CUDA:", torch.cuda.is_available())

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
unsloth: 2026.9.10
transformers: 5.5.0
trl: 0.24.0
accelerate: 1.15.0
torch: 2.11.0+cu128
CUDA: True

In [ ]:
from transformers.training_args import OptimizerNames

print("ADAMW_APEX_FUSED:", hasattr(OptimizerNames, "ADAMW_APEX_FUSED"))
print("ADAMW_8BIT:", hasattr(OptimizerNames, "ADAMW_8BIT"))

from trl import SFTTrainer
print("SFTTrainer import: OK")

ADAMW_APEX_FUSED: True
ADAMW_8BIT: True
SFTTrainer import: OK

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

CHECKPOINT_DIR = "/content/drive/MyDrive/clinical-gatekeeper-checkpoints"

import os
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

checkpoint_dirs = sorted([
    os.path.join(CHECKPOINT_DIR, d)
    for d in os.listdir(CHECKPOINT_DIR)
    if d.startswith("checkpoint-")
    and os.path.isdir(os.path.join(CHECKPOINT_DIR, d))
])

print("Checkpoint directory:", CHECKPOINT_DIR)
print("Existing checkpoints:", checkpoint_dirs)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Checkpoint directory: /content/drive/MyDrive/clinical-gatekeeper-checkpoints
Existing checkpoints: ['/content/drive/MyDrive/clinical-gatekeeper-checkpoints/checkpoint-1000', '/content/drive/MyDrive/clinical-gatekeeper-checkpoints/checkpoint-1200', '/content/drive/MyDrive/clinical-gatekeeper-checkpoints/checkpoint-800']

In [ ]:
import unsloth
import torch

from unsloth import FastLanguageModel

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/Llama-3.2-3B-Instruct-bnb-4bit",
    max_seq_length=2048,
    load_in_4bit=True,
)

model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
    ],
    lora_alpha=16,
    lora_dropout=0,
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=42,
)

print("Model + LoRA loaded successfully.")

==((====))==  Unsloth 2026.9.10: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

Unsloth: Will load unsloth/Llama-3.2-3B-Instruct-bnb-4bit as a legacy tokenizer.
Unsloth 2026.9.10 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.

Model + LoRA loaded successfully.

In [ ]:
import os

print("Files in /content:")
for f in os.listdir("/content"):
    if f.endswith(".jsonl"):
        print(" ", f)

Files in /content:

In [ ]:
from google.colab import files

uploaded = files.upload()

print("Uploaded files:")
for name in uploaded:
    print(name)

Saving train_chat.jsonl to train_chat.jsonl
Saving val_chat.jsonl to val_chat.jsonl
Uploaded files:
train_chat.jsonl
val_chat.jsonl

In [ ]:
from datasets import load_dataset

TRAIN_PATH = "/content/train_chat.jsonl"
VAL_PATH = "/content/val_chat.jsonl"

dataset = load_dataset(
    "json",
    data_files={
        "train": TRAIN_PATH,
        "val": VAL_PATH,
    },
)

print("Train rows:", len(dataset["train"]))
print("Val rows:", len(dataset["val"]))
print("Columns:", dataset["train"].column_names)
print("First row:", dataset["train"][0])

Generating train split: 0 examples [00:00, ? examples/s]

Generating val split: 0 examples [00:00, ? examples/s]

Train rows: 4500
Val rows: 500
Columns: ['messages']
First row: {'messages': [{'role': 'system', 'content': 'You are a clinical imaging quality assistant. Given DICOM quality metrics (blur, contrast, noise scores, overall state, and dominant defect), explain the defect and give a concise, actionable retake instruction.'}, {'role': 'user', 'content': '{"blur": 33.9, "contrast": 50.9, "noise": 91.3, "state": "REJECT", "dominant_defect": "sensor_noise"}'}, {'role': 'assistant', 'content': 'Image noise is contributing to reduced diagnostic clarity (noise score 91/100). Verify detector performance and repeat the acquisition if needed.'}]}

In [ ]:
def format_batch(examples):
    texts = []

    for messages in examples["messages"]:
        text = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=False,
        )
        texts.append(text)

    return {"text": texts}


dataset_text = dataset.map(
    format_batch,
    batched=True,
    remove_columns=["messages"],
)

print("Train rows:", len(dataset_text["train"]))
print("Val rows:", len(dataset_text["val"]))
print("Columns:", dataset_text["train"].column_names)
print("Sample formatted text:")
print(dataset_text["train"][0]["text"][:1000])

Map:   0%|          | 0/4500 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

Train rows: 4500
Val rows: 500
Columns: ['text']
Sample formatted text:
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 27 Sep 2026

You are a clinical imaging quality assistant. Given DICOM quality metrics (blur, contrast, noise scores, overall state, and dominant defect), explain the defect and give a concise, actionable retake instruction.<|eot_id|><|start_header_id|>user<|end_header_id|>

{"blur": 33.9, "contrast": 50.9, "noise": 91.3, "state": "REJECT", "dominant_defect": "sensor_noise"}<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Image noise is contributing to reduced diagnostic clarity (noise score 91/100). Verify detector performance and repeat the acquisition if needed.<|eot_id|>

In [ ]:
from transformers import TrainingArguments
from trl import SFTTrainer
import torch
import os

CHECKPOINT_DIR = "/content/drive/MyDrive/clinical-gatekeeper-checkpoints"

checkpoint_dirs = sorted([
    os.path.join(CHECKPOINT_DIR, d)
    for d in os.listdir(CHECKPOINT_DIR)
    if d.startswith("checkpoint-")
    and os.path.isdir(os.path.join(CHECKPOINT_DIR, d))
])

resume = len(checkpoint_dirs) > 0

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset_text["train"],
    eval_dataset=dataset_text["val"],
    dataset_text_field="text",
    max_seq_length=2048,
    args=TrainingArguments(
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,

        num_train_epochs=3,

        warmup_steps=51,
        learning_rate=2e-4,
        lr_scheduler_type="cosine",

        fp16=not torch.cuda.is_bf16_supported(),
        bf16=torch.cuda.is_bf16_supported(),

        logging_steps=10,

        eval_strategy="steps",
        eval_steps=100,

        save_strategy="steps",
        save_steps=200,
        save_total_limit=3,

        optim="adamw_8bit",

        output_dir=CHECKPOINT_DIR,
        report_to="none",
    ),
)

print("Trainer created successfully.")

Unsloth: We found double BOS tokens - we shall remove one automatically.

Unsloth: Tokenizing ["text"] (num_proc=2):   0%|          | 0/4500 [00:00<?, ? examples/s]

Unsloth: We found double BOS tokens - we shall remove one automatically.

Unsloth: Tokenizing ["text"] (num_proc=2):   0%|          | 0/500 [00:00<?, ? examples/s]

Trainer created successfully.

In [ ]:
print("Train rows:", len(dataset_text["train"]))
print("Val rows:", len(dataset_text["val"]))

print("Per-device batch size:", trainer.args.per_device_train_batch_size)
print("Gradient accumulation:", trainer.args.gradient_accumulation_steps)

print(
    "Effective batch size:",
    trainer.args.per_device_train_batch_size
    * trainer.args.gradient_accumulation_steps
)

print("Epochs:", trainer.args.num_train_epochs)
print("Warmup steps:", trainer.args.warmup_steps)
print("Learning rate:", trainer.args.learning_rate)
print("Eval every:", trainer.args.eval_steps)
print("Checkpoint every:", trainer.args.save_steps)
print("FP16:", trainer.args.fp16)
print("BF16:", trainer.args.bf16)
print("Optimizer:", trainer.args.optim)
print("Output directory:", trainer.args.output_dir)
print("Resume:", resume)

# Exact expected optimizer-step count
train_rows = len(dataset_text["train"])
effective_batch = (
    trainer.args.per_device_train_batch_size
    * trainer.args.gradient_accumulation_steps
)
steps_per_epoch = (train_rows + effective_batch - 1) // effective_batch
total_steps = steps_per_epoch * trainer.args.num_train_epochs

print("Steps per epoch:", steps_per_epoch)
print("Expected total optimizer steps:", total_steps)

Train rows: 4500
Val rows: 500
Per-device batch size: 2
Gradient accumulation: 4
Effective batch size: 8
Epochs: 3
Warmup steps: 51
Learning rate: 0.0002
Eval every: 100
Checkpoint every: 200
FP16: True
BF16: False
Optimizer: OptimizerNames.ADAMW_8BIT
Output directory: /content/drive/MyDrive/clinical-gatekeeper-checkpoints
Resume: True
Steps per epoch: 563
Expected total optimizer steps: 1689

In [ ]:
import time
start_time = time.time()
trainer_stats = trainer.train(
    resume_from_checkpoint=False
)
elapsed = time.time() - start_time

print("\n=======TRAINING COMPLETE========")
print(f"Wall-clock time; {elapsed / 3600:.2f} hours")
print(f"Final training loss: {trainer_stats.training_loss}")
print(f"Global steps: {trainer.state.global_step}")

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 4,500 | Num Epochs = 3 | Total steps = 1,689
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 24,313,856 of 3,237,063,680 (0.75% trained)
`use_return_dict` is deprecated! Use `return_dict` instead!
/usr/local/lib/python3.13/dist-packages/unsloth/import_fixes.py:3239: UserWarning: 'has_cuda' is deprecated, please use 'torch.backends.cuda.is_built()'
  return original(name)
/usr/local/lib/python3.13/dist-packages/unsloth/import_fixes.py:3239: UserWarning: 'has_cudnn' is deprecated, please use 'torch.backends.cudnn.is_available()'
  return original(name)
/usr/local/lib/python3.13/dist-packages/unsloth/import_fixes.py:3239: UserWarning: 'has_mps' is deprecated, please use 'torch.backends.mps.is_built()'
  return original(name)
/usr/local/lib/python3.13/dist-packages/unsloth/import_fixes.py:3239: UserWarning: 'has_mkldnn' is deprecated, please use 'torch.backends.mkldnn.is_available()'
  return original(name)

Unsloth: Restored added_tokens_decoder metadata in /content/drive/MyDrive/clinical-gatekeeper-checkpoints/checkpoint-200/tokenizer_config.json.
Unsloth: Restored added_tokens_decoder metadata in /content/drive/MyDrive/clinical-gatekeeper-checkpoints/checkpoint-400/tokenizer_config.json.
Unsloth: Restored added_tokens_decoder metadata in /content/drive/MyDrive/clinical-gatekeeper-checkpoints/checkpoint-600/tokenizer_config.json.
Unsloth: Restored added_tokens_decoder metadata in /content/drive/MyDrive/clinical-gatekeeper-checkpoints/checkpoint-800/tokenizer_config.json.
Unsloth: Restored added_tokens_decoder metadata in /content/drive/MyDrive/clinical-gatekeeper-checkpoints/checkpoint-1000/tokenizer_config.json.
Unsloth: Restored added_tokens_decoder metadata in /content/drive/MyDrive/clinical-gatekeeper-checkpoints/checkpoint-1200/tokenizer_config.json.
Unsloth: Restored added_tokens_decoder metadata in /content/drive/MyDrive/clinical-gatekeeper-checkpoints/checkpoint-1400/tokenizer_config.json.
Unsloth: Restored added_tokens_decoder metadata in /content/drive/MyDrive/clinical-gatekeeper-checkpoints/checkpoint-1600/tokenizer_config.json.
Unsloth: Restored added_tokens_decoder metadata in /content/drive/MyDrive/clinical-gatekeeper-checkpoints/checkpoint-1689/tokenizer_config.json.

=======TRAINING COMPLETE========
Wall-clock time; 1.39 hours
Final training loss: 0.190883578175691
Global steps: 1689

In [ ]:
import os

checkpoints = sorted(
    d for d in os.listdir(CHECKPOINT_DIR)
    if d.startswith("checkpoint-")
    and os.path.isdir(os.path.join(CHECKPOINT_DIR, d))
)

print("Checkpoints currently on Drive:")
for d in checkpoints:
    print(d)

print("\nCount:", len(checkpoints))

Checkpoints currently on Drive:
checkpoint-1400
checkpoint-1600
checkpoint-1689

Count: 3

In [ ]:
import os

for d in ["checkpoint-1400", "checkpoint-1600", "checkpoint-1689"]:
    path = os.path.join(CHECKPOINT_DIR, d)

    total_bytes = 0
    for root, dirs, files in os.walk(path):
        for f in files:
            total_bytes += os.path.getsize(os.path.join(root, f))

    print(f"{d}: {total_bytes / (1024**3):.2f} GB")

checkpoint-1400: 0.15 GB
checkpoint-1600: 0.15 GB
checkpoint-1689: 0.15 GB

In [ ]:
!ls -la /content/drive/MyDrive/clinical-gatekeeper-checkpoints/

total 22
drwx------ 5 root root 4096 Sep 27 06:30 .
drwx------ 4 root root 4096 Sep 27 05:00 ..
drwx------ 2 root root 4096 Sep 27 06:16 checkpoint-1400
drwx------ 2 root root 4096 Sep 27 06:25 checkpoint-1600
drwx------ 2 root root 4096 Sep 27 06:30 checkpoint-1689
-rw------- 1 root root 1534 Sep 27 06:30 README.md

In [ ]:
import json
import random
import re
from unsloth import FastLanguageModel

CHECKPOINT_PATH = (
    "/content/drive/MyDrive/"
    "clinical-gatekeeper-checkpoints/checkpoint-1689"
)

SYSTEM_PROMPT = (
    "You are a clinical imaging quality assistant. Given DICOM quality metrics "
    "(blur, contrast, noise scores, overall state, and dominant defect), explain "
    "the defect and give a concise, actionable retake instruction."
)

# Load final checkpoint
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=CHECKPOINT_PATH,
    max_seq_length=2048,
    load_in_4bit=True,
)

FastLanguageModel.for_inference(model)

print("Final checkpoint loaded.")

==((====))==  Unsloth 2026.9.10: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

Unsloth: Will load /content/drive/MyDrive/clinical-gatekeeper-checkpoints/checkpoint-1689 as a legacy tokenizer.

Final checkpoint loaded.

In [ ]:
VAL_PATH = "/content/val_chat.jsonl"

with open(VAL_PATH, "r", encoding="utf-8") as f:
    val_rows = [json.loads(line) for line in f]

print("Validation rows:", len(val_rows))

Validation rows: 500

In [ ]:
import json
import torch

SYSTEM_PROMPT = (
    "You are a clinical imaging quality assistant. Given DICOM quality metrics "
    "(blur, contrast, noise scores, overall state, and dominant defect), explain "
    "the defect and give a concise, actionable retake instruction."
)

def generate(metrics_dict):
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": json.dumps(metrics_dict)},
    ]

    inputs = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        return_tensors="pt",
        return_dict=True,
    )

    inputs = {
        key: value.to("cuda")
        for key, value in inputs.items()
    }

    outputs = model.generate(
        input_ids=inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        max_new_tokens=80,
        use_cache=True,
        do_sample=False,
    )

    generated_ids = outputs[0][inputs["input_ids"].shape[1]:]

    return tokenizer.decode(
        generated_ids,
        skip_special_tokens=True,
    ).strip()

In [ ]:
def extract_val_example(row):
    messages = row["messages"]

    user_message = next(
        m["content"] for m in messages if m["role"] == "user"
    )

    expected = next(
        m["content"] for m in messages if m["role"] == "assistant"
    )

    metrics = json.loads(user_message)

    return metrics, expected

In [ ]:
import random

random.seed(42)
sample_rows = random.sample(val_rows, 15)

for i, row in enumerate(sample_rows, 1):
    metrics, expected = extract_val_example(row)
    generated = generate(metrics)

    print("\n" + "=" * 80)
    print(f"VAL EXAMPLE {i}/15")
    print("INPUT:   ", metrics)
    print("EXPECTED:", expected)
    print("GOT:     ", generated)

Both `max_new_tokens` (=80) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=80) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

================================================================================
VAL EXAMPLE 1/15
INPUT:    {'blur': 16.2, 'contrast': 53.5, 'noise': 20.7, 'state': 'ACCEPT', 'dominant_defect': 'none'}
EXPECTED: The reported metrics indicate acceptable image quality. No corrective acquisition is required.
GOT:      All reported quality metrics are within the acceptable range. No retake is needed.

Both `max_new_tokens` (=80) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

================================================================================
VAL EXAMPLE 2/15
INPUT:    {'blur': 21.8, 'contrast': 50.3, 'noise': 29.1, 'state': 'ACCEPT', 'dominant_defect': 'none'}
EXPECTED: The reported metrics indicate acceptable image quality. No corrective acquisition is required.
GOT:      All reported quality metrics are within the acceptable range. No retake is needed.

Both `max_new_tokens` (=80) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

================================================================================
VAL EXAMPLE 3/15
INPUT:    {'blur': 30.7, 'contrast': 45.7, 'noise': 21.7, 'state': 'BORDERLINE', 'dominant_defect': 'low_contrast'}
EXPECTED: Low contrast is the dominant quality defect (contrast score 46/100). Review the exposure technique and repeat the acquisition.
GOT:      The image shows mild low contrast at a score of 46/100. Adjust the acquisition technique according to the imaging protocol.

Both `max_new_tokens` (=80) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

================================================================================
VAL EXAMPLE 4/15
INPUT:    {'blur': 36.3, 'contrast': 36.2, 'noise': 20.9, 'state': 'BORDERLINE', 'dominant_defect': 'low_contrast'}
EXPECTED: The image shows mild low contrast at a score of 36/100. Adjust the acquisition technique according to the imaging protocol.
GOT:      The image shows mild low contrast at a score of 36/100. Adjust the acquisition technique according to the imaging protocol.

Both `max_new_tokens` (=80) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

================================================================================
VAL EXAMPLE 5/15
INPUT:    {'blur': 33.4, 'contrast': 69.3, 'noise': 17.4, 'state': 'REJECT', 'dominant_defect': 'high_contrast'}
EXPECTED: The contrast score is 69/100, indicating elevated contrast. Review the exposure settings and repeat the acquisition.
GOT:      The image shows moderate high contrast at a score of 69/100. Review the acquisition settings before retaking the image.

Both `max_new_tokens` (=80) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

================================================================================
VAL EXAMPLE 6/15
INPUT:    {'blur': 36.2, 'contrast': 47.7, 'noise': 38.9, 'state': 'BORDERLINE', 'dominant_defect': 'low_contrast'}
EXPECTED: The image shows mild low contrast at a score of 48/100. Adjust the acquisition technique according to the imaging protocol.
GOT:      The contrast score is 48/100, indicating reduced contrast. Review the exposure settings and repeat the image.

Both `max_new_tokens` (=80) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

================================================================================
VAL EXAMPLE 7/15
INPUT:    {'blur': 21.5, 'contrast': 50.1, 'noise': 97.2, 'state': 'REJECT', 'dominant_defect': 'sensor_noise'}
EXPECTED: Image noise is contributing to reduced diagnostic clarity (noise score 97/100). Verify detector performance and repeat the acquisition if needed.
GOT:      The noise score of 97/100 indicates severe signal degradation. Inspect the detector for artifacts before retaking the image.

Both `max_new_tokens` (=80) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

================================================================================
VAL EXAMPLE 8/15
INPUT:    {'blur': 4.1, 'contrast': 57.8, 'noise': 25.2, 'state': 'ACCEPT', 'dominant_defect': 'none'}
EXPECTED: The reported metrics indicate acceptable image quality. No corrective acquisition is required.
GOT:      All reported quality metrics are within the acceptable range. No retake is needed.

Both `max_new_tokens` (=80) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

================================================================================
VAL EXAMPLE 9/15
INPUT:    {'blur': 7.0, 'contrast': 56.2, 'noise': 21.8, 'state': 'ACCEPT', 'dominant_defect': 'none'}
EXPECTED: No significant image-quality defect is identified (blur 7, contrast 56, noise 22). The image can proceed without retake.
GOT:      All reported quality metrics are within the acceptable range. No retake is needed.

Both `max_new_tokens` (=80) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

================================================================================
VAL EXAMPLE 10/15
INPUT:    {'blur': 2.9, 'contrast': 54.7, 'noise': 12.3, 'state': 'ACCEPT', 'dominant_defect': 'none'}
EXPECTED: The reported metrics indicate acceptable image quality. No corrective acquisition is required.
GOT:      All reported quality metrics are within the acceptable range. No retake is needed.

Both `max_new_tokens` (=80) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

================================================================================
VAL EXAMPLE 11/15
INPUT:    {'blur': 26.0, 'contrast': 57.5, 'noise': 16.4, 'state': 'ACCEPT', 'dominant_defect': 'none'}
EXPECTED: No significant image-quality defect is identified (blur 26, contrast 58, noise 16). The image can proceed without retake.
GOT:      All reported quality metrics are within the acceptable range. No retake is needed.

Both `max_new_tokens` (=80) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

================================================================================
VAL EXAMPLE 12/15
INPUT:    {'blur': 36.0, 'contrast': 57.1, 'noise': 94.5, 'state': 'REJECT', 'dominant_defect': 'sensor_noise'}
EXPECTED: Image noise is contributing to reduced diagnostic clarity (noise score 94/100). Verify detector performance and repeat the acquisition if needed.
GOT:      The noise score of 94/100 indicates severe signal degradation. Inspect the detector for artifacts before retaking the image.

Both `max_new_tokens` (=80) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

================================================================================
VAL EXAMPLE 13/15
INPUT:    {'blur': 27.3, 'contrast': 61.5, 'noise': 28.5, 'state': 'BORDERLINE', 'dominant_defect': 'high_contrast'}
EXPECTED: The contrast score is 62/100, indicating elevated contrast. Review the exposure settings and repeat the acquisition.
GOT:      The image shows mild high contrast at a score of 62/100. Review the acquisition settings before retaking the image.

Both `max_new_tokens` (=80) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

================================================================================
VAL EXAMPLE 14/15
INPUT:    {'blur': 12.5, 'contrast': 13.1, 'noise': 31.2, 'state': 'REJECT', 'dominant_defect': 'low_contrast'}
EXPECTED: The contrast score is 13/100, indicating reduced contrast. Review the exposure settings and repeat the image.
GOT:      The image shows severe low contrast at a score of 13/100. Adjust the acquisition technique according to the imaging protocol.

================================================================================
VAL EXAMPLE 15/15
INPUT:    {'blur': 2.4, 'contrast': 58.3, 'noise': 26.1, 'state': 'ACCEPT', 'dominant_defect': 'none'}
EXPECTED: The reported metrics indicate acceptable image quality. No corrective acquisition is required.
GOT:      All reported quality metrics are within the acceptable range. No retake is needed.

In [ ]:
edge_cases = [
    {
        "blur": 100.0,
        "contrast": 100.0,
        "noise": 100.0,
        "state": "REJECT",
        "dominant_defect": "motion_blur",
    },
    {
        "blur": 65.0,
        "contrast": 65.0,
        "noise": 65.0,
        "state": "BORDERLINE",
        "dominant_defect": "sensor_noise",
    },
    {
        "blur": 0.0,
        "contrast": 0.0,
        "noise": 0.0,
        "state": "ACCEPT",
        "dominant_defect": "none",
    },
    {
        "blur": 90.0,
        "contrast": 5.0,
        "noise": 88.0,
        "state": "REJECT",
        "dominant_defect": "motion_blur",
    },
]

for i, metrics in enumerate(edge_cases, 1):
    generated = generate(metrics)

    print("\n" + "=" * 80)
    print(f"EDGE CASE {i}/4")
    print("INPUT:", metrics)
    print("GOT:  ", generated)

Both `max_new_tokens` (=80) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=80) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

================================================================================
EDGE CASE 1/4
INPUT: {'blur': 100.0, 'contrast': 100.0, 'noise': 100.0, 'state': 'REJECT', 'dominant_defect': 'motion_blur'}
GOT:   Motion blur is the dominant image-quality defect (blur score 100/100). Keep the patient still during exposure and repeat the acquisition.

Both `max_new_tokens` (=80) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

================================================================================
EDGE CASE 2/4
INPUT: {'blur': 65.0, 'contrast': 65.0, 'noise': 65.0, 'state': 'BORDERLINE', 'dominant_defect': 'sensor_noise'}
GOT:   The noise score of 65/100 indicates mild signal degradation. Inspect the detector for artifacts before retaking the image.

Both `max_new_tokens` (=80) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

================================================================================
EDGE CASE 3/4
INPUT: {'blur': 0.0, 'contrast': 0.0, 'noise': 0.0, 'state': 'ACCEPT', 'dominant_defect': 'none'}
GOT:   All reported quality metrics are within the acceptable range. No retake is needed.

================================================================================
EDGE CASE 4/4
INPUT: {'blur': 90.0, 'contrast': 5.0, 'noise': 88.0, 'state': 'REJECT', 'dominant_defect': 'motion_blur'}
GOT:   Motion blur is the dominant image-quality defect (blur score 90/100). Keep the patient still during exposure and repeat the acquisition.